CREATE TABLE `bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`petOwnerId` int NOT NULL,
	`petId` int NOT NULL,
	`veterinarianId` int,
	`clinicId` int,
	`serviceType` enum('consultation','examination','surgery','grooming','vaccination','other') NOT NULL,
	`bookingDate` timestamp NOT NULL,
	`duration` int,
	`status` enum('pending','confirmed','in_progress','completed','cancelled','no_show') DEFAULT 'pending',
	`notes` longtext,
	`consultationFee` decimal(10,2),
	`commissionPercentage` decimal(5,2) DEFAULT '20',
	`platformCommission` decimal(10,2),
	`vetEarnings` decimal(10,2),
	`paymentStatus` enum('pending','completed','refunded') DEFAULT 'pending',
	`paymentMethod` varchar(255),
	`transactionId` varchar(255),
	`cancellationReason` varchar(255),
	`cancelledBy` enum('pet_owner','vet','clinic','admin'),
	`cancelledAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bookings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `clinicProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clinicId` int NOT NULL,
	`ownerId` int NOT NULL,
	`registrationFeeStatus` enum('pending','paid') DEFAULT 'pending',
	`registrationFeePaidAt` timestamp,
	`registrationFeeAmount` decimal(10,2),
	`licenseNumber` varchar(255),
	`licenseImageUrl` varchar(512),
	`coverImageUrl` varchar(512),
	`verified` boolean DEFAULT false,
	`verifiedAt` timestamp,
	`rating` decimal(3,2) DEFAULT '0',
	`totalReviews` int DEFAULT 0,
	`services` json,
	`servicesAr` json,
	`staffCount` int,
	`yearEstablished` int,
	`bankAccount` varchar(255),
	`bankName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clinicProfiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `clinicProfiles_clinicId_unique` UNIQUE(`clinicId`)
);
--> statement-breakpoint
CREATE TABLE `clinicVets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clinicId` int NOT NULL,
	`veterinarianId` int NOT NULL,
	`position` varchar(255),
	`joinedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `clinicVets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceNumber` varchar(255) NOT NULL,
	`buyerId` int NOT NULL,
	`sellerId` int,
	`invoiceType` enum('product_order','service_booking') NOT NULL,
	`bookingId` int,
	`subtotal` decimal(10,2) NOT NULL,
	`taxAmount` decimal(10,2) DEFAULT '0',
	`shippingCost` decimal(10,2) DEFAULT '0',
	`platformCommission` decimal(10,2) DEFAULT '0',
	`totalAmount` decimal(10,2) NOT NULL,
	`paymentStatus` enum('pending','completed','failed','refunded') DEFAULT 'pending',
	`paymentMethod` varchar(255),
	`transactionId` varchar(255),
	`shippingAddress` longtext,
	`shippingStatus` enum('pending','shipped','delivered','cancelled') DEFAULT 'pending',
	`trackingNumber` varchar(255),
	`notes` longtext,
	`lineItems` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_invoiceNumber_unique` UNIQUE(`invoiceNumber`)
);
--> statement-breakpoint
CREATE TABLE `ratingsReviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reviewerId` int NOT NULL,
	`targetType` enum('vet','clinic','product') NOT NULL,
	`targetId` int NOT NULL,
	`rating` int NOT NULL,
	`title` varchar(255),
	`comment` longtext,
	`verifiedBooking` boolean DEFAULT false,
	`bookingId` int,
	`helpful` int DEFAULT 0,
	`unhelpful` int DEFAULT 0,
	`response` longtext,
	`responseAt` timestamp,
	`respondedBy` int,
	`imageUrls` json,
	`status` enum('pending','approved','rejected') DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ratingsReviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shoppingCart` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`productId` int NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`priceAtAddTime` decimal(10,2),
	`addedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shoppingCart_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`walletId` int NOT NULL,
	`transactionType` enum('booking_payment','product_sale','commission_deduction','withdrawal','refund','bonus','registration_fee') NOT NULL,
	`amount` decimal(15,2) NOT NULL,
	`description` varchar(512),
	`relatedBookingId` int,
	`relatedInvoiceId` int,
	`status` enum('pending','completed','failed') DEFAULT 'pending',
	`paymentMethod` varchar(255),
	`externalTransactionId` varchar(255),
	`notes` longtext,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vendorProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`businessNameAr` varchar(255),
	`description` longtext,
	`descriptionAr` longtext,
	`logoUrl` varchar(512),
	`coverImageUrl` varchar(512),
	`businessLicense` varchar(255),
	`businessLicenseImageUrl` varchar(512),
	`category` enum('organic_food','natural_treats','eco_supplies','toys_enrichment','grooming','training_tools','supplements','bedding','other') NOT NULL,
	`website` varchar(512),
	`phone` varchar(20),
	`email` varchar(320),
	`address` varchar(512),
	`city` varchar(255),
	`country` varchar(255),
	`rating` decimal(3,2) DEFAULT '0',
	`totalReviews` int DEFAULT 0,
	`verified` boolean DEFAULT false,
	`verifiedAt` timestamp,
	`totalProducts` int DEFAULT 0,
	`totalSales` int DEFAULT 0,
	`responseTime` int,
	`returnPolicy` longtext,
	`shippingInfo` longtext,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendorProfiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `vendorProfiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `veterinarianProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`licenseNumber` varchar(255) NOT NULL,
	`licenseImageUrl` varchar(512),
	`specializations` json,
	`specializationsAr` json,
	`bio` longtext,
	`bioAr` longtext,
	`profileImageUrl` varchar(512),
	`clinicId` int,
	`isFreelance` boolean DEFAULT true,
	`registrationFeeStatus` enum('pending','paid','free') DEFAULT 'free',
	`registrationFeePaidAt` timestamp,
	`verified` boolean DEFAULT false,
	`verifiedAt` timestamp,
	`rating` decimal(3,2) DEFAULT '0',
	`totalReviews` int DEFAULT 0,
	`responseTime` int,
	`yearsOfExperience` int,
	`languages` json,
	`consultationFee` decimal(10,2),
	`availability` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `veterinarianProfiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `veterinarianProfiles_userId_unique` UNIQUE(`userId`),
	CONSTRAINT `veterinarianProfiles_licenseNumber_unique` UNIQUE(`licenseNumber`)
);
--> statement-breakpoint
CREATE TABLE `wallets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`walletType` enum('vet','clinic','vendor','pet_owner') NOT NULL,
	`balance` decimal(15,2) DEFAULT '0',
	`totalEarnings` decimal(15,2) DEFAULT '0',
	`totalWithdrawals` decimal(15,2) DEFAULT '0',
	`totalCommissions` decimal(15,2) DEFAULT '0',
	`bankAccount` varchar(255),
	`bankName` varchar(255),
	`accountHolder` varchar(255),
	`verificationStatus` enum('unverified','pending','verified') DEFAULT 'unverified',
	`verifiedAt` timestamp,
	`lastWithdrawalAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wallets_id` PRIMARY KEY(`id`),
	CONSTRAINT `wallets_userId_unique` UNIQUE(`userId`)
);
