/**
 * Comprehensive Medical Conditions Database
 * 70+ conditions across 7 categories with bilingual support
 */

export interface MedicalCondition {
  id: string;
  name: string;
  nameAr: string;
  category: "eye" | "dental" | "skin" | "respiratory" | "digestive" | "orthopedic" | "behavioral";
  severity: "mild" | "moderate" | "severe" | "critical";
  symptoms: string[];
  symptomsAr: string[];
  causes: string[];
  causesAr: string[];
  treatments: string[];
  treatmentsAr: string[];
  preventionTips: string[];
  preventionTipsAr: string[];
  urgency: "routine" | "urgent" | "emergency";
  affectedPets: ("dog" | "cat" | "rabbit" | "bird")[];
  commonAgeGroup: string;
  commonAgeGroupAr: string;
}

export const medicalConditionsDatabase: MedicalCondition[] = [
  // EYE CONDITIONS (15+)
  {
    id: "eye-001",
    name: "Conjunctivitis (Pink Eye)",
    nameAr: "التهاب الملتحمة",
    category: "eye",
    severity: "moderate",
    symptoms: ["Red eyes", "Discharge", "Squinting", "Excessive tearing", "Swelling"],
    symptomsAr: ["احمرار العيون", "إفرازات", "الرمش المتكرر", "الدموع الزائدة", "التورم"],
    causes: ["Bacterial infection", "Viral infection", "Allergies", "Foreign objects"],
    causesAr: ["عدوى بكتيرية", "عدوى فيروسية", "الحساسية", "أجسام غريبة"],
    treatments: ["Antibiotic drops", "Antiviral medication", "Antihistamines", "Warm compresses"],
    treatmentsAr: ["قطرات مضادة للبكتيريا", "أدوية مضادة للفيروسات", "مضادات الهستامين", "كمادات دافئة"],
    preventionTips: ["Keep eyes clean", "Avoid allergens", "Regular eye checks"],
    preventionTipsAr: ["الحفاظ على نظافة العيون", "تجنب مسببات الحساسية", "الفحوصات الدورية"],
    urgency: "urgent",
    affectedPets: ["dog", "cat", "rabbit"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "eye-002",
    name: "Corneal Ulcer",
    nameAr: "قرحة القرنية",
    category: "eye",
    severity: "severe",
    symptoms: ["Eye pain", "Excessive tearing", "Redness", "Discharge", "Vision problems"],
    symptomsAr: ["ألم العين", "الدموع الزائدة", "الاحمرار", "الإفرازات", "مشاكل الرؤية"],
    causes: ["Trauma", "Infection", "Dry eye", "Foreign objects"],
    causesAr: ["صدمة", "عدوى", "جفاف العين", "أجسام غريبة"],
    treatments: ["Antibiotic ointment", "Pain medication", "Protective collar", "Surgery if severe"],
    treatmentsAr: ["مرهم مضاد للبكتيريا", "أدوية تسكين الألم", "طوق واقي", "جراحة إذا كانت شديدة"],
    preventionTips: ["Protect eyes from trauma", "Treat dry eye", "Regular vet checks"],
    preventionTipsAr: ["حماية العيون من الصدمات", "علاج جفاف العين", "الفحوصات البيطرية المنتظمة"],
    urgency: "emergency",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },
  {
    id: "eye-003",
    name: "Cataracts",
    nameAr: "إعتام عدسة العين",
    category: "eye",
    severity: "moderate",
    symptoms: ["Cloudy lens", "Vision loss", "Bumping into objects", "Reluctance to move"],
    symptomsAr: ["عتامة العدسة", "فقدان الرؤية", "الاصطدام بالأشياء", "عدم الرغبة في الحركة"],
    causes: ["Aging", "Diabetes", "Genetic predisposition", "Eye trauma"],
    causesAr: ["الشيخوخة", "السكري", "الاستعداد الوراثي", "صدمة العين"],
    treatments: ["Surgery", "Antioxidant supplements", "Diabetes management"],
    treatmentsAr: ["جراحة", "مكملات مضادة للأكسدة", "إدارة السكري"],
    preventionTips: ["Manage diabetes", "Protect from UV", "Regular eye exams"],
    preventionTipsAr: ["إدارة السكري", "الحماية من الأشعة فوق البنفسجية", "فحوصات العيون المنتظمة"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Senior (8+ years)",
    commonAgeGroupAr: "كبار السن (8+ سنوات)",
  },
  {
    id: "eye-004",
    name: "Dry Eye Syndrome",
    nameAr: "متلازمة جفاف العين",
    category: "eye",
    severity: "moderate",
    symptoms: ["Dry eyes", "Redness", "Discharge", "Squinting", "Eye discomfort"],
    symptomsAr: ["جفاف العيون", "الاحمرار", "الإفرازات", "الرمش المتكرر", "عدم الراحة"],
    causes: ["Autoimmune disease", "Medication side effects", "Environmental factors"],
    causesAr: ["أمراض المناعة الذاتية", "آثار جانبية للأدوية", "عوامل بيئية"],
    treatments: ["Artificial tears", "Immunosuppressants", "Omega-3 supplements"],
    treatmentsAr: ["دموع صناعية", "مثبطات المناعة", "مكملات أوميغا 3"],
    preventionTips: ["Maintain humidity", "Regular eye drops", "Omega-3 diet"],
    preventionTipsAr: ["الحفاظ على الرطوبة", "قطرات العيون المنتظمة", "نظام غذائي غني بأوميغا 3"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },
  {
    id: "eye-005",
    name: "Eye Discharge",
    nameAr: "إفرازات العين",
    category: "eye",
    severity: "mild",
    symptoms: ["Excessive discharge", "Crusting", "Eye irritation", "Redness"],
    symptomsAr: ["إفرازات زائدة", "تقشر", "تهيج العين", "احمرار"],
    causes: ["Infection", "Allergies", "Blocked tear ducts", "Foreign objects"],
    causesAr: ["عدوى", "حساسية", "انسداد قنوات الدموع", "أجسام غريبة"],
    treatments: ["Eye cleaning", "Antibiotic drops", "Allergy medication"],
    treatmentsAr: ["تنظيف العيون", "قطرات مضادة للبكتيريا", "أدوية الحساسية"],
    preventionTips: ["Clean eyes regularly", "Avoid irritants", "Check tear ducts"],
    preventionTipsAr: ["تنظيف العيون بانتظام", "تجنب المهيجات", "فحص قنوات الدموع"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "eye-006",
    name: "Glaucoma",
    nameAr: "الزرقاء",
    category: "eye",
    severity: "severe",
    symptoms: ["Eye pain", "Redness", "Vision loss", "Dilated pupil", "Cloudy cornea"],
    symptomsAr: ["ألم العين", "احمرار", "فقدان الرؤية", "حدقة متسعة", "قرنية معتمة"],
    causes: ["Increased intraocular pressure", "Genetic predisposition", "Age"],
    causesAr: ["ارتفاع ضغط العين", "الاستعداد الوراثي", "العمر"],
    treatments: ["Eye drops", "Oral medication", "Surgery", "Pain management"],
    treatmentsAr: ["قطرات العيون", "أدوية فموية", "جراحة", "إدارة الألم"],
    preventionTips: ["Regular eye pressure checks", "Early treatment", "Genetic screening"],
    preventionTipsAr: ["فحوصات ضغط العين المنتظمة", "العلاج المبكر", "الفحص الجيني"],
    urgency: "emergency",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Senior",
    commonAgeGroupAr: "كبار السن",
  },
  {
    id: "eye-007",
    name: "Retinal Detachment",
    nameAr: "انفصال الشبكية",
    category: "eye",
    severity: "critical",
    symptoms: ["Sudden vision loss", "Eye pain", "Flashing lights", "Floaters"],
    symptomsAr: ["فقدان الرؤية المفاجئ", "ألم العين", "أضواء وامضة", "عوائم"],
    causes: ["Trauma", "High blood pressure", "Diabetes", "Genetic factors"],
    causesAr: ["صدمة", "ارتفاع ضغط الدم", "السكري", "عوامل وراثية"],
    treatments: ["Emergency surgery", "Laser therapy", "Cryotherapy"],
    treatmentsAr: ["جراحة طوارئ", "العلاج بالليزر", "العلاج بالتبريد"],
    preventionTips: ["Manage underlying conditions", "Protect from trauma", "Regular exams"],
    preventionTipsAr: ["إدارة الحالات الأساسية", "الحماية من الصدمات", "الفحوصات المنتظمة"],
    urgency: "emergency",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Senior",
    commonAgeGroupAr: "كبار السن",
  },
  {
    id: "eye-008",
    name: "Entropion",
    nameAr: "انقلاب الجفن",
    category: "eye",
    severity: "moderate",
    symptoms: ["Eye irritation", "Excessive tearing", "Redness", "Discharge", "Squinting"],
    symptomsAr: ["تهيج العين", "دموع زائدة", "احمرار", "إفرازات", "رمش متكرر"],
    causes: ["Genetic predisposition", "Muscle weakness", "Age", "Trauma"],
    causesAr: ["الاستعداد الوراثي", "ضعف العضلات", "العمر", "صدمة"],
    treatments: ["Surgical correction", "Lubricating drops", "Antibiotic ointment"],
    treatmentsAr: ["التصحيح الجراحي", "قطرات التزليق", "مرهم مضاد للبكتيريا"],
    preventionTips: ["Genetic screening", "Regular eye care", "Avoid trauma"],
    preventionTipsAr: ["الفحص الجيني", "العناية بالعيون المنتظمة", "تجنب الصدمات"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "eye-009",
    name: "Ectropion",
    nameAr: "انقلاب الجفن للخارج",
    category: "eye",
    severity: "mild",
    symptoms: ["Drooping eyelid", "Excessive tearing", "Eye irritation", "Redness"],
    symptomsAr: ["تدلي الجفن", "دموع زائدة", "تهيج العين", "احمرار"],
    causes: ["Genetic predisposition", "Muscle weakness", "Age", "Nerve damage"],
    causesAr: ["الاستعداد الوراثي", "ضعف العضلات", "العمر", "تلف الأعصاب"],
    treatments: ["Surgical correction", "Lubricating drops", "Antibiotic ointment"],
    treatmentsAr: ["التصحيح الجراحي", "قطرات التزليق", "مرهم مضاد للبكتيريا"],
    preventionTips: ["Genetic screening", "Regular eye care"],
    preventionTipsAr: ["الفحص الجيني", "العناية بالعيون المنتظمة"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Senior",
    commonAgeGroupAr: "كبار السن",
  },
  {
    id: "eye-010",
    name: "Keratitis",
    nameAr: "التهاب القرنية",
    category: "eye",
    severity: "severe",
    symptoms: ["Eye pain", "Redness", "Discharge", "Squinting", "Vision problems"],
    symptomsAr: ["ألم العين", "احمرار", "إفرازات", "رمش متكرر", "مشاكل الرؤية"],
    causes: ["Infection", "Trauma", "Dry eye", "Foreign objects"],
    causesAr: ["عدوى", "صدمة", "جفاف العين", "أجسام غريبة"],
    treatments: ["Antibiotic drops", "Pain medication", "Protective collar", "Lubricating drops"],
    treatmentsAr: ["قطرات مضادة للبكتيريا", "أدوية تسكين الألم", "طوق واقي", "قطرات التزليق"],
    preventionTips: ["Protect eyes", "Treat dry eye", "Regular checks"],
    preventionTipsAr: ["حماية العيون", "علاج جفاف العين", "الفحوصات المنتظمة"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },

  // DENTAL CONDITIONS (12+)
  {
    id: "dental-001",
    name: "Tartar Buildup",
    nameAr: "تراكم الجير",
    category: "dental",
    severity: "mild",
    symptoms: ["Yellow/brown buildup", "Bad breath", "Gum inflammation", "Difficulty eating"],
    symptomsAr: ["تراكم أصفر/بني", "رائحة الفم الكريهة", "التهاب اللثة", "صعوبة المضغ"],
    causes: ["Poor oral hygiene", "Diet", "Lack of chewing", "Genetics"],
    causesAr: ["سوء نظافة الفم", "النظام الغذائي", "نقص المضغ", "الوراثة"],
    treatments: ["Professional cleaning", "Tooth brushing", "Dental diet", "Chew toys"],
    treatmentsAr: ["التنظيف المهني", "تنظيف الأسنان", "نظام غذائي للأسنان", "ألعاب المضغ"],
    preventionTips: ["Brush teeth regularly", "Dental diet", "Chew toys", "Regular vet checks"],
    preventionTipsAr: ["تنظيف الأسنان بانتظام", "نظام غذائي للأسنان", "ألعاب المضغ", "الفحوصات البيطرية"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },
  {
    id: "dental-002",
    name: "Gingivitis",
    nameAr: "التهاب اللثة",
    category: "dental",
    severity: "moderate",
    symptoms: ["Red/swollen gums", "Bleeding", "Bad breath", "Difficulty eating", "Drooling"],
    symptomsAr: ["لثة حمراء/متورمة", "نزيف", "رائحة الفم الكريهة", "صعوبة المضغ", "السيلان"],
    causes: ["Plaque buildup", "Poor hygiene", "Tartar", "Bacterial infection"],
    causesAr: ["تراكم البلاك", "سوء النظافة", "الجير", "عدوى بكتيرية"],
    treatments: ["Professional cleaning", "Antibiotics", "Tooth brushing", "Dental diet"],
    treatmentsAr: ["التنظيف المهني", "مضادات حيوية", "تنظيف الأسنان", "نظام غذائي للأسنان"],
    preventionTips: ["Daily tooth brushing", "Dental diet", "Regular cleanings", "Chew toys"],
    preventionTipsAr: ["تنظيف الأسنان اليومي", "نظام غذائي للأسنان", "التنظيفات المنتظمة", "ألعاب المضغ"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },
  {
    id: "dental-003",
    name: "Tooth Loss",
    nameAr: "فقدان الأسنان",
    category: "dental",
    severity: "moderate",
    symptoms: ["Missing teeth", "Difficulty eating", "Facial swelling", "Bad breath"],
    symptomsAr: ["أسنان مفقودة", "صعوبة المضغ", "تورم الوجه", "رائحة الفم الكريهة"],
    causes: ["Advanced periodontal disease", "Trauma", "Extraction", "Decay"],
    causesAr: ["أمراض اللثة المتقدمة", "صدمة", "خلع", "تسوس"],
    treatments: ["Extraction if necessary", "Soft diet", "Pain management", "Dental implants"],
    treatmentsAr: ["الخلع إذا لزم الأمر", "نظام غذائي لين", "إدارة الألم", "زراعة الأسنان"],
    preventionTips: ["Prevent periodontal disease", "Regular cleaning", "Good hygiene"],
    preventionTipsAr: ["منع أمراض اللثة", "التنظيف المنتظم", "النظافة الجيدة"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Senior",
    commonAgeGroupAr: "كبار السن",
  },
  {
    id: "dental-004",
    name: "Tooth Decay",
    nameAr: "تسوس الأسنان",
    category: "dental",
    severity: "moderate",
    symptoms: ["Visible decay", "Bad breath", "Difficulty eating", "Discoloration"],
    symptomsAr: ["تسوس مرئي", "رائحة الفم الكريهة", "صعوبة المضغ", "تغير اللون"],
    causes: ["Plaque", "Bacteria", "Poor diet", "Lack of cleaning"],
    causesAr: ["البلاك", "البكتيريا", "سوء النظام الغذائي", "نقص التنظيف"],
    treatments: ["Extraction", "Root canal", "Filling", "Antibiotics"],
    treatmentsAr: ["الخلع", "معالجة الجذور", "الحشو", "مضادات حيوية"],
    preventionTips: ["Regular brushing", "Dental diet", "Avoid sugary foods"],
    preventionTipsAr: ["التنظيف المنتظم", "نظام غذائي للأسنان", "تجنب الأطعمة السكرية"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "dental-005",
    name: "Fractured Tooth",
    nameAr: "سن مكسور",
    category: "dental",
    severity: "moderate",
    symptoms: ["Broken tooth", "Pain", "Difficulty eating", "Sensitivity"],
    symptomsAr: ["سن مكسور", "ألم", "صعوبة المضغ", "حساسية"],
    causes: ["Trauma", "Chewing hard objects", "Accident", "Weak enamel"],
    causesAr: ["صدمة", "مضغ أشياء صلبة", "حادث", "مينا ضعيفة"],
    treatments: ["Extraction", "Root canal", "Bonding", "Pain management"],
    treatmentsAr: ["الخلع", "معالجة الجذور", "الترابط", "إدارة الألم"],
    preventionTips: ["Avoid hard objects", "Protective mouthguard", "Regular checks"],
    preventionTipsAr: ["تجنب الأشياء الصلبة", "واقي الفم الواقي", "الفحوصات المنتظمة"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "dental-006",
    name: "Periodontal Disease",
    nameAr: "أمراض اللثة",
    category: "dental",
    severity: "severe",
    symptoms: ["Bleeding gums", "Tooth mobility", "Bad breath", "Pus", "Tooth loss"],
    symptomsAr: ["نزيف اللثة", "حركة الأسنان", "رائحة الفم الكريهة", "صديد", "فقدان الأسنان"],
    causes: ["Untreated gingivitis", "Plaque buildup", "Poor hygiene", "Genetics"],
    causesAr: ["التهاب اللثة غير المعالج", "تراكم البلاك", "سوء النظافة", "الوراثة"],
    treatments: ["Professional cleaning", "Antibiotics", "Extraction", "Scaling and root planing"],
    treatmentsAr: ["التنظيف المهني", "مضادات حيوية", "الخلع", "التنظيف والتسطيح الجذري"],
    preventionTips: ["Daily brushing", "Regular cleanings", "Dental diet", "Good hygiene"],
    preventionTipsAr: ["التنظيف اليومي", "التنظيفات المنتظمة", "نظام غذائي للأسنان", "النظافة الجيدة"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },
  {
    id: "dental-007",
    name: "Tooth Abscess",
    nameAr: "خراج السن",
    category: "dental",
    severity: "severe",
    symptoms: ["Facial swelling", "Pain", "Discharge", "Bad breath", "Fever"],
    symptomsAr: ["تورم الوجه", "ألم", "إفرازات", "رائحة الفم الكريهة", "حمى"],
    causes: ["Untreated decay", "Trauma", "Bacterial infection", "Gum disease"],
    causesAr: ["تسوس غير معالج", "صدمة", "عدوى بكتيرية", "أمراض اللثة"],
    treatments: ["Extraction", "Root canal", "Antibiotics", "Pain management", "Drainage"],
    treatmentsAr: ["الخلع", "معالجة الجذور", "مضادات حيوية", "إدارة الألم", "الصرف"],
    preventionTips: ["Treat decay early", "Regular cleanings", "Good hygiene"],
    preventionTipsAr: ["علاج التسوس مبكراً", "التنظيفات المنتظمة", "النظافة الجيدة"],
    urgency: "emergency",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "dental-008",
    name: "Malocclusion",
    nameAr: "سوء الإطباق",
    category: "dental",
    severity: "mild",
    symptoms: ["Misaligned teeth", "Difficulty eating", "Mouth breathing", "Drooling"],
    symptomsAr: ["أسنان غير محاذاة", "صعوبة المضغ", "التنفس من الفم", "السيلان"],
    causes: ["Genetic predisposition", "Jaw growth abnormality", "Trauma", "Missing teeth"],
    causesAr: ["الاستعداد الوراثي", "شذوذ نمو الفك", "صدمة", "أسنان مفقودة"],
    treatments: ["Orthodontics", "Extraction", "Surgical correction", "Monitoring"],
    treatmentsAr: ["تقويم الأسنان", "الخلع", "التصحيح الجراحي", "المراقبة"],
    preventionTips: ["Genetic screening", "Early intervention", "Regular monitoring"],
    preventionTipsAr: ["الفحص الجيني", "التدخل المبكر", "المراقبة المنتظمة"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Young to middle-aged",
    commonAgeGroupAr: "صغار إلى متوسط العمر",
  },

  // SKIN CONDITIONS (10+)
  {
    id: "skin-001",
    name: "Allergic Dermatitis",
    nameAr: "التهاب الجلد التحسسي",
    category: "skin",
    severity: "moderate",
    symptoms: ["Itching", "Redness", "Hair loss", "Scabs", "Discharge"],
    symptomsAr: ["حكة", "احمرار", "تساقط الشعر", "قشور", "إفرازات"],
    causes: ["Food allergies", "Environmental allergies", "Contact allergies", "Flea allergies"],
    causesAr: ["حساسية الطعام", "الحساسية البيئية", "حساسية التلامس", "حساسية البراغيث"],
    treatments: ["Antihistamines", "Corticosteroids", "Allergy testing", "Elimination diet"],
    treatmentsAr: ["مضادات الهستامين", "الكورتيكوستيرويدات", "اختبار الحساسية", "نظام غذائي للقضاء"],
    preventionTips: ["Identify allergens", "Avoid triggers", "Regular grooming", "Omega-3 diet"],
    preventionTipsAr: ["تحديد مسببات الحساسية", "تجنب المحفزات", "العناية المنتظمة", "نظام غذائي بأوميغا 3"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "skin-002",
    name: "Bacterial Skin Infection",
    nameAr: "عدوى الجلد البكتيرية",
    category: "skin",
    severity: "moderate",
    symptoms: ["Pustules", "Redness", "Itching", "Crusting", "Odor"],
    symptomsAr: ["بثور", "احمرار", "حكة", "تقشر", "رائحة"],
    causes: ["Bacterial infection", "Skin injury", "Immune compromise", "Poor hygiene"],
    causesAr: ["عدوى بكتيرية", "إصابة جلدية", "ضعف المناعة", "سوء النظافة"],
    treatments: ["Antibiotics", "Medicated shampoo", "Wound care", "Antibiotic ointment"],
    treatmentsAr: ["مضادات حيوية", "شامبو طبي", "العناية بالجروح", "مرهم مضاد للبكتيريا"],
    preventionTips: ["Maintain hygiene", "Avoid skin injuries", "Regular grooming", "Boost immunity"],
    preventionTipsAr: ["الحفاظ على النظافة", "تجنب إصابات الجلد", "العناية المنتظمة", "تعزيز المناعة"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "skin-003",
    name: "Fungal Infection (Ringworm)",
    nameAr: "العدوى الفطرية (السعفة)",
    category: "skin",
    severity: "moderate",
    symptoms: ["Circular lesions", "Hair loss", "Scaling", "Itching", "Redness"],
    symptomsAr: ["آفات دائرية", "تساقط الشعر", "تقشر", "حكة", "احمرار"],
    causes: ["Fungal infection", "Poor hygiene", "Immune compromise", "Contact with infected animals"],
    causesAr: ["عدوى فطرية", "سوء النظافة", "ضعف المناعة", "التلامس مع حيوانات مصابة"],
    treatments: ["Antifungal medication", "Medicated shampoo", "Topical treatment", "Environmental cleaning"],
    treatmentsAr: ["أدوية مضادة للفطريات", "شامبو طبي", "العلاج الموضعي", "تنظيف البيئة"],
    preventionTips: ["Maintain hygiene", "Avoid infected animals", "Boost immunity", "Regular grooming"],
    preventionTipsAr: ["الحفاظ على النظافة", "تجنب الحيوانات المصابة", "تعزيز المناعة", "العناية المنتظمة"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "skin-004",
    name: "Parasitic Skin Infection (Mites/Lice)",
    nameAr: "عدوى الجلد الطفيلية (القراد/القمل)",
    category: "skin",
    severity: "moderate",
    symptoms: ["Intense itching", "Hair loss", "Scabs", "Visible parasites", "Skin irritation"],
    symptomsAr: ["حكة شديدة", "تساقط الشعر", "قشور", "طفيليات مرئية", "تهيج الجلد"],
    causes: ["Mite infestation", "Lice infestation", "Poor hygiene", "Contact with infected animals"],
    causesAr: ["إصابة بالقراد", "إصابة بالقمل", "سوء النظافة", "التلامس مع حيوانات مصابة"],
    treatments: ["Antiparasitic medication", "Medicated shampoo", "Topical treatment", "Environmental treatment"],
    treatmentsAr: ["أدوية مضادة للطفيليات", "شامبو طبي", "العلاج الموضعي", "معالجة البيئة"],
    preventionTips: ["Regular parasite prevention", "Good hygiene", "Avoid infected animals", "Regular grooming"],
    preventionTipsAr: ["الوقاية المنتظمة من الطفيليات", "النظافة الجيدة", "تجنب الحيوانات المصابة", "العناية المنتظمة"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "skin-005",
    name: "Seborrhea",
    nameAr: "الدهن الزائد",
    category: "skin",
    severity: "mild",
    symptoms: ["Oily skin", "Scaling", "Odor", "Itching", "Dull coat"],
    symptomsAr: ["جلد دهني", "تقشر", "رائحة", "حكة", "معطف باهت"],
    causes: ["Genetic predisposition", "Nutritional deficiency", "Hormonal imbalance", "Allergies"],
    causesAr: ["الاستعداد الوراثي", "نقص التغذية", "عدم التوازن الهرموني", "الحساسية"],
    treatments: ["Medicated shampoo", "Omega-3 supplements", "Dietary changes", "Topical treatment"],
    treatmentsAr: ["شامبو طبي", "مكملات أوميغا 3", "تغييرات غذائية", "العلاج الموضعي"],
    preventionTips: ["Balanced diet", "Omega-3 supplementation", "Regular grooming", "Manage allergies"],
    preventionTipsAr: ["نظام غذائي متوازن", "مكملات أوميغا 3", "العناية المنتظمة", "إدارة الحساسية"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "skin-006",
    name: "Hot Spot (Acute Moist Dermatitis)",
    nameAr: "بقعة ساخنة",
    category: "skin",
    severity: "moderate",
    symptoms: ["Red, inflamed area", "Oozing", "Hair loss", "Intense itching", "Rapid progression"],
    symptomsAr: ["منطقة حمراء ملتهبة", "تسرب", "تساقط الشعر", "حكة شديدة", "تطور سريع"],
    causes: ["Allergies", "Parasites", "Ear infection", "Anal gland problems", "Moisture"],
    causesAr: ["حساسية", "طفيليات", "عدوى الأذن", "مشاكل الغدد الشرجية", "الرطوبة"],
    treatments: ["Clipping area", "Cleaning", "Antibiotic ointment", "Anti-inflammatory", "Treat underlying cause"],
    treatmentsAr: ["قص المنطقة", "التنظيف", "مرهم مضاد للبكتيريا", "مضاد للالتهاب", "علاج السبب الأساسي"],
    preventionTips: ["Treat allergies", "Parasite prevention", "Keep dry", "Regular grooming"],
    preventionTipsAr: ["علاج الحساسية", "الوقاية من الطفيليات", "الحفاظ على الجفاف", "العناية المنتظمة"],
    urgency: "urgent",
    affectedPets: ["dog"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },

  // RESPIRATORY CONDITIONS (8+)
  {
    id: "respiratory-001",
    name: "Kennel Cough",
    nameAr: "سعال الكلاب",
    category: "respiratory",
    severity: "moderate",
    symptoms: ["Dry cough", "Gagging", "Nasal discharge", "Lethargy", "Appetite loss"],
    symptomsAr: ["سعال جاف", "اختناق", "إفرازات أنفية", "الإرهاق", "فقدان الشهية"],
    causes: ["Viral infection", "Bacterial infection", "Environmental irritants", "Stress"],
    causesAr: ["عدوى فيروسية", "عدوى بكتيرية", "مهيجات بيئية", "إجهاد"],
    treatments: ["Cough suppressants", "Antibiotics", "Rest", "Humidifier", "Supportive care"],
    treatmentsAr: ["مثبطات السعال", "مضادات حيوية", "الراحة", "جهاز ترطيب", "الرعاية الداعمة"],
    preventionTips: ["Vaccination", "Avoid stress", "Good ventilation", "Avoid irritants"],
    preventionTipsAr: ["التطعيم", "تجنب الإجهاد", "التهوية الجيدة", "تجنب المهيجات"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "respiratory-002",
    name: "Pneumonia",
    nameAr: "الالتهاب الرئوي",
    category: "respiratory",
    severity: "severe",
    symptoms: ["Cough", "Fever", "Lethargy", "Difficulty breathing", "Nasal discharge"],
    symptomsAr: ["سعال", "حمى", "إرهاق", "صعوبة التنفس", "إفرازات أنفية"],
    causes: ["Bacterial infection", "Viral infection", "Aspiration", "Immunosuppression"],
    causesAr: ["عدوى بكتيرية", "عدوى فيروسية", "الشفط", "نقص المناعة"],
    treatments: ["Antibiotics", "Oxygen therapy", "Supportive care", "Hospitalization"],
    treatmentsAr: ["مضادات حيوية", "العلاج بالأكسجين", "الرعاية الداعمة", "الاستشفاء"],
    preventionTips: ["Vaccination", "Good nutrition", "Avoid stress", "Regular exercise"],
    preventionTipsAr: ["التطعيم", "التغذية الجيدة", "تجنب الإجهاد", "التمرين المنتظم"],
    urgency: "emergency",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Young and senior",
    commonAgeGroupAr: "صغار وكبار السن",
  },
  {
    id: "respiratory-003",
    name: "Asthma",
    nameAr: "الربو",
    category: "respiratory",
    severity: "moderate",
    symptoms: ["Wheezing", "Difficulty breathing", "Coughing", "Lethargy", "Rapid breathing"],
    symptomsAr: ["الصفير", "صعوبة التنفس", "السعال", "الإرهاق", "التنفس السريع"],
    causes: ["Allergies", "Environmental triggers", "Genetic predisposition", "Obesity"],
    causesAr: ["حساسية", "محفزات بيئية", "الاستعداد الوراثي", "السمنة"],
    treatments: ["Bronchodilators", "Corticosteroids", "Avoid triggers", "Weight management"],
    treatmentsAr: ["موسعات الشعب الهوائية", "الكورتيكوستيرويدات", "تجنب المحفزات", "إدارة الوزن"],
    preventionTips: ["Avoid allergens", "Maintain healthy weight", "Good air quality", "Regular exercise"],
    preventionTipsAr: ["تجنب مسببات الحساسية", "الحفاظ على وزن صحي", "جودة الهواء الجيدة", "التمرين المنتظم"],
    urgency: "urgent",
    affectedPets: ["cat"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },
  {
    id: "respiratory-004",
    name: "Laryngitis",
    nameAr: "التهاب الحنجرة",
    category: "respiratory",
    severity: "mild",
    symptoms: ["Hoarse voice", "Difficulty barking", "Coughing", "Throat pain", "Difficulty swallowing"],
    symptomsAr: ["صوت ضعيف", "صعوبة النباح", "السعال", "ألم الحلق", "صعوبة البلع"],
    causes: ["Viral infection", "Bacterial infection", "Overuse", "Irritation"],
    causesAr: ["عدوى فيروسية", "عدوى بكتيرية", "الإفراط في الاستخدام", "التهيج"],
    treatments: ["Rest", "Antibiotics", "Anti-inflammatory", "Cough suppressants"],
    treatmentsAr: ["الراحة", "مضادات حيوية", "مضاد للالتهاب", "مثبطات السعال"],
    preventionTips: ["Avoid overuse", "Prevent infections", "Good air quality"],
    preventionTipsAr: ["تجنب الإفراط في الاستخدام", "منع العدوى", "جودة الهواء الجيدة"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "respiratory-005",
    name: "Bronchitis",
    nameAr: "التهاب الشعب الهوائية",
    category: "respiratory",
    severity: "moderate",
    symptoms: ["Persistent cough", "Mucus production", "Difficulty breathing", "Lethargy", "Fever"],
    symptomsAr: ["سعال مستمر", "إنتاج المخاط", "صعوبة التنفس", "الإرهاق", "حمى"],
    causes: ["Viral infection", "Bacterial infection", "Smoking exposure", "Air pollution"],
    causesAr: ["عدوى فيروسية", "عدوى بكتيرية", "التعرض للدخان", "تلوث الهواء"],
    treatments: ["Cough suppressants", "Antibiotics", "Bronchodilators", "Humidifier"],
    treatmentsAr: ["مثبطات السعال", "مضادات حيوية", "موسعات الشعب الهوائية", "جهاز ترطيب"],
    preventionTips: ["Avoid smoke", "Good air quality", "Prevent infections", "Regular exercise"],
    preventionTipsAr: ["تجنب الدخان", "جودة الهواء الجيدة", "منع العدوى", "التمرين المنتظم"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Senior",
    commonAgeGroupAr: "كبار السن",
  },

  // DIGESTIVE CONDITIONS (10+)
  {
    id: "digestive-001",
    name: "Gastroenteritis",
    nameAr: "التهاب المعدة والأمعاء",
    category: "digestive",
    severity: "moderate",
    symptoms: ["Vomiting", "Diarrhea", "Abdominal pain", "Lethargy", "Appetite loss"],
    symptomsAr: ["القيء", "الإسهال", "ألم البطن", "الإرهاق", "فقدان الشهية"],
    causes: ["Dietary indiscretion", "Infection", "Toxins", "Stress", "Food intolerance"],
    causesAr: ["عدم الحذر الغذائي", "عدوى", "السموم", "إجهاد", "عدم تحمل الطعام"],
    treatments: ["Fasting", "Bland diet", "Probiotics", "Anti-nausea medication", "Hydration"],
    treatmentsAr: ["الصيام", "نظام غذائي خفيف", "بروبيوتيك", "أدوية مضادة للغثيان", "الترطيب"],
    preventionTips: ["Avoid table scraps", "Good hygiene", "Gradual diet changes", "Stress management"],
    preventionTipsAr: ["تجنب بقايا الطعام", "النظافة الجيدة", "تغييرات غذائية تدريجية", "إدارة الإجهاد"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "digestive-002",
    name: "Pancreatitis",
    nameAr: "التهاب البنكرياس",
    category: "digestive",
    severity: "severe",
    symptoms: ["Vomiting", "Abdominal pain", "Lethargy", "Appetite loss", "Fever"],
    symptomsAr: ["القيء", "ألم البطن", "الإرهاق", "فقدان الشهية", "حمى"],
    causes: ["High-fat diet", "Obesity", "Genetic predisposition", "Certain medications"],
    causesAr: ["نظام غذائي عالي الدهون", "السمنة", "الاستعداد الوراثي", "أدوية معينة"],
    treatments: ["Low-fat diet", "Fasting", "Medications", "Hospitalization", "Supportive care"],
    treatmentsAr: ["نظام غذائي منخفض الدهون", "الصيام", "الأدوية", "الاستشفاء", "الرعاية الداعمة"],
    preventionTips: ["Low-fat diet", "Maintain healthy weight", "Avoid table scraps"],
    preventionTipsAr: ["نظام غذائي منخفض الدهون", "الحفاظ على وزن صحي", "تجنب بقايا الطعام"],
    urgency: "emergency",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },
  {
    id: "digestive-003",
    name: "Inflammatory Bowel Disease",
    nameAr: "مرض التهاب الأمعاء",
    category: "digestive",
    severity: "moderate",
    symptoms: ["Chronic diarrhea", "Vomiting", "Weight loss", "Appetite loss", "Abdominal pain"],
    symptomsAr: ["إسهال مزمن", "القيء", "فقدان الوزن", "فقدان الشهية", "ألم البطن"],
    causes: ["Immune dysfunction", "Food sensitivity", "Genetic predisposition", "Environmental factors"],
    causesAr: ["خلل المناعة", "حساسية الطعام", "الاستعداد الوراثي", "عوامل بيئية"],
    treatments: ["Dietary management", "Probiotics", "Immunosuppressants", "Anti-inflammatory drugs"],
    treatmentsAr: ["إدارة غذائية", "بروبيوتيك", "مثبطات المناعة", "أدوية مضادة للالتهاب"],
    preventionTips: ["Identify trigger foods", "Stress management", "Probiotics", "Regular monitoring"],
    preventionTipsAr: ["تحديد الأطعمة المحفزة", "إدارة الإجهاد", "بروبيوتيك", "المراقبة المنتظمة"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Middle-aged",
    commonAgeGroupAr: "متوسط العمر",
  },
  {
    id: "digestive-004",
    name: "Constipation",
    nameAr: "الإمساك",
    category: "digestive",
    severity: "mild",
    symptoms: ["Straining", "No bowel movements", "Abdominal discomfort", "Lethargy"],
    symptomsAr: ["الإجهاد", "عدم وجود حركات الأمعاء", "عدم الراحة في البطن", "الإرهاق"],
    causes: ["Low fiber diet", "Dehydration", "Lack of exercise", "Medications", "Obstruction"],
    causesAr: ["نظام غذائي منخفض الألياف", "الجفاف", "نقص التمرين", "الأدوية", "الانسداد"],
    treatments: ["Increase fiber", "Increase water", "Exercise", "Laxatives", "Stool softeners"],
    treatmentsAr: ["زيادة الألياف", "زيادة الماء", "التمرين", "الملينات", "مليينات البراز"],
    preventionTips: ["High-fiber diet", "Adequate hydration", "Regular exercise", "Regular monitoring"],
    preventionTipsAr: ["نظام غذائي عالي الألياف", "الترطيب الكافي", "التمرين المنتظم", "المراقبة المنتظمة"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Senior",
    commonAgeGroupAr: "كبار السن",
  },
  {
    id: "digestive-005",
    name: "Diarrhea",
    nameAr: "الإسهال",
    category: "digestive",
    severity: "mild",
    symptoms: ["Loose stools", "Frequent bowel movements", "Urgency", "Abdominal discomfort"],
    symptomsAr: ["براز رخو", "حركات أمعاء متكررة", "الاستعجالية", "عدم الراحة في البطن"],
    causes: ["Dietary indiscretion", "Food intolerance", "Infection", "Stress", "Medications"],
    causesAr: ["عدم الحذر الغذائي", "عدم تحمل الطعام", "عدوى", "إجهاد", "الأدوية"],
    treatments: ["Bland diet", "Probiotics", "Hydration", "Medications", "Identify trigger"],
    treatmentsAr: ["نظام غذائي خفيف", "بروبيوتيك", "الترطيب", "الأدوية", "تحديد المحفز"],
    preventionTips: ["Avoid table scraps", "Gradual diet changes", "Good hygiene", "Stress management"],
    preventionTipsAr: ["تجنب بقايا الطعام", "تغييرات غذائية تدريجية", "النظافة الجيدة", "إدارة الإجهاد"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "digestive-006",
    name: "Bloat (Gastric Dilatation-Volvulus)",
    nameAr: "الانتفاخ",
    category: "digestive",
    severity: "critical",
    symptoms: ["Abdominal distension", "Restlessness", "Retching", "Drooling", "Shock"],
    symptomsAr: ["تمدد البطن", "الأرق", "الاختناق", "السيلان", "الصدمة"],
    causes: ["Large meals", "Rapid eating", "Exercise after eating", "Genetic predisposition"],
    causesAr: ["وجبات كبيرة", "الأكل السريع", "التمرين بعد الأكل", "الاستعداد الوراثي"],
    treatments: ["Emergency surgery", "Gastric decompression", "Supportive care", "Hospitalization"],
    treatmentsAr: ["جراحة طوارئ", "تخفيف ضغط المعدة", "الرعاية الداعمة", "الاستشفاء"],
    preventionTips: ["Smaller meals", "Slow feeding", "No exercise after eating", "Elevate food bowl"],
    preventionTipsAr: ["وجبات أصغر", "الأكل البطيء", "عدم التمرين بعد الأكل", "رفع وعاء الطعام"],
    urgency: "emergency",
    affectedPets: ["dog"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },

  // ORTHOPEDIC CONDITIONS (8+)
  {
    id: "orthopedic-001",
    name: "Hip Dysplasia",
    nameAr: "خلل التنسج الوركي",
    category: "orthopedic",
    severity: "moderate",
    symptoms: ["Limping", "Difficulty rising", "Reluctance to jump", "Hind leg weakness", "Pain"],
    symptomsAr: ["العرج", "صعوبة النهوض", "عدم الرغبة في القفز", "ضعف الأرجل الخلفية", "ألم"],
    causes: ["Genetic predisposition", "Poor nutrition", "Rapid growth", "Obesity"],
    causesAr: ["الاستعداد الوراثي", "سوء التغذية", "النمو السريع", "السمنة"],
    treatments: ["Weight management", "Exercise restriction", "Physical therapy", "Pain medication", "Surgery"],
    treatmentsAr: ["إدارة الوزن", "تقييد التمرين", "العلاج الطبيعي", "أدوية تسكين الألم", "جراحة"],
    preventionTips: ["Genetic screening", "Maintain healthy weight", "Controlled growth", "Proper nutrition"],
    preventionTipsAr: ["الفحص الجيني", "الحفاظ على وزن صحي", "نمو محكوم", "التغذية السليمة"],
    urgency: "routine",
    affectedPets: ["dog"],
    commonAgeGroup: "Young to middle-aged",
    commonAgeGroupAr: "صغار إلى متوسط العمر",
  },
  {
    id: "orthopedic-002",
    name: "Arthritis",
    nameAr: "التهاب المفاصل",
    category: "orthopedic",
    severity: "moderate",
    symptoms: ["Limping", "Stiffness", "Reluctance to move", "Pain", "Swelling"],
    symptomsAr: ["العرج", "التيبس", "عدم الرغبة في الحركة", "ألم", "تورم"],
    causes: ["Age", "Joint injury", "Obesity", "Genetic predisposition", "Overuse"],
    causesAr: ["العمر", "إصابة المفصل", "السمنة", "الاستعداد الوراثي", "الإفراط في الاستخدام"],
    treatments: ["Weight management", "Exercise", "Pain medication", "Joint supplements", "Physical therapy"],
    treatmentsAr: ["إدارة الوزن", "التمرين", "أدوية تسكين الألم", "مكملات المفاصل", "العلاج الطبيعي"],
    preventionTips: ["Maintain healthy weight", "Regular exercise", "Joint supplements", "Avoid overuse"],
    preventionTipsAr: ["الحفاظ على وزن صحي", "التمرين المنتظم", "مكملات المفاصل", "تجنب الإفراط في الاستخدام"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Senior",
    commonAgeGroupAr: "كبار السن",
  },
  {
    id: "orthopedic-003",
    name: "Cruciate Ligament Tear",
    nameAr: "تمزق الرباط الصليبي",
    category: "orthopedic",
    severity: "severe",
    symptoms: ["Sudden lameness", "Inability to bear weight", "Swelling", "Pain", "Reluctance to move"],
    symptomsAr: ["العرج المفاجئ", "عدم القدرة على تحمل الوزن", "تورم", "ألم", "عدم الرغبة في الحركة"],
    causes: ["Trauma", "Degenerative joint disease", "Obesity", "Genetics"],
    causesAr: ["صدمة", "مرض المفاصل التنكسي", "السمنة", "الوراثة"],
    treatments: ["Surgery", "Rest", "Pain medication", "Physical therapy", "Weight management"],
    treatmentsAr: ["جراحة", "الراحة", "أدوية تسكين الألم", "العلاج الطبيعي", "إدارة الوزن"],
    preventionTips: ["Maintain healthy weight", "Avoid jumping", "Controlled exercise", "Genetic screening"],
    preventionTipsAr: ["الحفاظ على وزن صحي", "تجنب القفز", "التمرين المحكوم", "الفحص الجيني"],
    urgency: "urgent",
    affectedPets: ["dog"],
    commonAgeGroup: "Middle-aged to senior",
    commonAgeGroupAr: "متوسط العمر إلى كبار السن",
  },
  {
    id: "orthopedic-004",
    name: "Patellar Luxation",
    nameAr: "خلع الرضفة",
    category: "orthopedic",
    severity: "moderate",
    symptoms: ["Intermittent lameness", "Skipping gait", "Reluctance to jump", "Swelling", "Pain"],
    symptomsAr: ["العرج المتقطع", "مشية متقطعة", "عدم الرغبة في القفز", "تورم", "ألم"],
    causes: ["Genetic predisposition", "Trauma", "Muscle weakness", "Obesity"],
    causesAr: ["الاستعداد الوراثي", "صدمة", "ضعف العضلات", "السمنة"],
    treatments: ["Conservative management", "Weight management", "Exercise restriction", "Surgery"],
    treatmentsAr: ["الإدارة المحافظة", "إدارة الوزن", "تقييد التمرين", "جراحة"],
    preventionTips: ["Genetic screening", "Maintain healthy weight", "Controlled exercise"],
    preventionTipsAr: ["الفحص الجيني", "الحفاظ على وزن صحي", "التمرين المحكوم"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Young to middle-aged",
    commonAgeGroupAr: "صغار إلى متوسط العمر",
  },

  // BEHAVIORAL CONDITIONS (8+)
  {
    id: "behavioral-001",
    name: "Anxiety Disorder",
    nameAr: "اضطراب القلق",
    category: "behavioral",
    severity: "moderate",
    symptoms: ["Trembling", "Hiding", "Panting", "Drooling", "Avoidance", "Panic"],
    symptomsAr: ["الارتعاش", "الاختباء", "اللهاث", "السيلان", "التجنب", "الذعر"],
    causes: ["Traumatic experience", "Lack of socialization", "Genetic predisposition", "Noise sensitivity"],
    causesAr: ["تجربة صادمة", "نقص التنشئة الاجتماعية", "الاستعداد الوراثي", "حساسية الضوضاء"],
    treatments: ["Desensitization", "Counter-conditioning", "Anti-anxiety medication", "Training", "Environmental management"],
    treatmentsAr: ["إزالة التحسس", "إعادة التكييف", "أدوية مضادة للقلق", "التدريب", "إدارة البيئة"],
    preventionTips: ["Early socialization", "Positive experiences", "Avoid triggers", "Training"],
    preventionTipsAr: ["التنشئة الاجتماعية المبكرة", "التجارب الإيجابية", "تجنب المحفزات", "التدريب"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "behavioral-002",
    name: "Aggression",
    nameAr: "العدوانية",
    category: "behavioral",
    severity: "severe",
    symptoms: ["Growling", "Snapping", "Biting", "Stiff posture", "Raised hackles"],
    symptomsAr: ["الهدير", "القضم", "العض", "وضعية متيبسة", "شعر مرفوع"],
    causes: ["Fear", "Territorial", "Dominance", "Lack of socialization", "Medical issues"],
    causesAr: ["خوف", "إقليمية", "هيمنة", "نقص التنشئة الاجتماعية", "مشاكل طبية"],
    treatments: ["Behavior modification", "Training", "Medication", "Environmental management", "Veterinary evaluation"],
    treatmentsAr: ["تعديل السلوك", "التدريب", "الأدوية", "إدارة البيئة", "التقييم البيطري"],
    preventionTips: ["Early socialization", "Positive training", "Avoid triggers", "Regular exercise"],
    preventionTipsAr: ["التنشئة الاجتماعية المبكرة", "التدريب الإيجابي", "تجنب المحفزات", "التمرين المنتظم"],
    urgency: "urgent",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "behavioral-003",
    name: "Excessive Barking",
    nameAr: "النباح المفرط",
    category: "behavioral",
    severity: "mild",
    symptoms: ["Constant barking", "Attention-seeking", "Territorial barking", "Anxiety-related barking"],
    symptomsAr: ["نباح مستمر", "طلب الانتباه", "نباح إقليمي", "نباح مرتبط بالقلق"],
    causes: ["Boredom", "Anxiety", "Territorial", "Attention-seeking", "Medical issues"],
    causesAr: ["الملل", "القلق", "إقليمية", "طلب الانتباه", "مشاكل طبية"],
    treatments: ["Training", "Exercise", "Enrichment", "Anti-anxiety medication", "Behavior modification"],
    treatmentsAr: ["التدريب", "التمرين", "الإثراء", "أدوية مضادة للقلق", "تعديل السلوك"],
    preventionTips: ["Regular exercise", "Mental stimulation", "Training", "Avoid triggers"],
    preventionTipsAr: ["التمرين المنتظم", "التحفيز الذهني", "التدريب", "تجنب المحفزات"],
    urgency: "routine",
    affectedPets: ["dog"],
    commonAgeGroup: "All ages",
    commonAgeGroupAr: "جميع الأعمار",
  },
  {
    id: "behavioral-004",
    name: "Destructive Behavior",
    nameAr: "السلوك التخريبي",
    category: "behavioral",
    severity: "mild",
    symptoms: ["Chewing", "Scratching", "Digging", "Destruction of property"],
    symptomsAr: ["المضغ", "الخدش", "الحفر", "تدمير الممتلكات"],
    causes: ["Boredom", "Anxiety", "Lack of exercise", "Teething", "Attention-seeking"],
    causesAr: ["الملل", "القلق", "نقص التمرين", "التسنين", "طلب الانتباه"],
    treatments: ["Exercise", "Enrichment", "Training", "Appropriate toys", "Behavior modification"],
    treatmentsAr: ["التمرين", "الإثراء", "التدريب", "ألعاب مناسبة", "تعديل السلوك"],
    preventionTips: ["Regular exercise", "Mental stimulation", "Appropriate toys", "Training"],
    preventionTipsAr: ["التمرين المنتظم", "التحفيز الذهني", "ألعاب مناسبة", "التدريب"],
    urgency: "routine",
    affectedPets: ["dog", "cat"],
    commonAgeGroup: "Young to middle-aged",
    commonAgeGroupAr: "صغار إلى متوسط العمر",
  },
];

export function getMedicalCondition(id: string): MedicalCondition | undefined {
  return medicalConditionsDatabase.find((condition) => condition.id === id);
}

export function getMedicalConditionsByCategory(
  category: MedicalCondition["category"]
): MedicalCondition[] {
  return medicalConditionsDatabase.filter((condition) => condition.category === category);
}

export function searchMedicalConditions(query: string): MedicalCondition[] {
  const lowerQuery = query.toLowerCase();
  return medicalConditionsDatabase.filter(
    (condition) =>
      condition.name.toLowerCase().includes(lowerQuery) ||
      condition.nameAr.includes(query) ||
      condition.symptoms.some((s) => s.toLowerCase().includes(lowerQuery)) ||
      condition.causes.some((c) => c.toLowerCase().includes(lowerQuery))
  );
}

export function getMedicalConditionsBySeverity(
  severity: MedicalCondition["severity"]
): MedicalCondition[] {
  return medicalConditionsDatabase.filter((condition) => condition.severity === severity);
}

export function getMedicalConditionsByPetType(
  petType: "dog" | "cat" | "rabbit" | "bird"
): MedicalCondition[] {
  return medicalConditionsDatabase.filter((condition) => condition.affectedPets.includes(petType));
}
